version: "3"

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - MY

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      RESULTS_TABLE_NAME: ${RESULTS_TABLE_NAME}
      OUTPUT_FILE_NAME: ${OUTPUT_FILE_NAME}
    volumes:
      - ./app/data:/app/data
#      - ./app/app.py:/app/app.py
    depends_on:
      - db
#      db:
#        condition: service_healthy
    networks:
      - MY

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - MY

volumes:
  db_data:

networks:
  MY:


